name: Scribe Lint

on:
  push

jobs:
  run_lint:
    name: Run python linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install python dependencies
        run: |
          uv sync

      - name: Run MyPy for type checking
        run: |
          make lint-ci
