name: Pytest

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync

    - name: Run pytest
      run: |
        uv run pytest -vvv
